- id: light_off_leave
  alias: Turn off lights when I leave
  trigger:
  - entity_id: device_tracker.jc_motox4
    platform: state
    to: not_home
  action:
  - entity_id:
    - light.bedroom
    service: light.turn_off
- id: light_on_arrive
  alias: Turn on lights when I arrive home
  trigger:
  - entity_id: device_tracker.jc_motox4
    from: not_home
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.xmfjvdpx_mk6p55
      state: home
    - after: sunset
      after_offset: '-1:30:00'
      condition: sun
  action:
  - data:
      brightness: 200
      rgb_color:
      - 255
      - 198
      - 102
    entity_id:
    - light.bedroom
    service: light.turn_on
- id: set_start_theme
  alias: Set Theme on Startup
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: main
- id: weather_forecast
  alias: Weather Forecast
  trigger:
  - at: '5:30:00'
    hours: 5
    minutes: 30
    platform: time
    seconds: 0
  action:
  - data_template:
      message: 'The weather for {{ states.sensor.pws_weather_1d.attributes.friendly_name
        }} is{{ '':'' }} {{ states.sensor.pws_weather_1d.state }} {{ states.sensor.pws_weather_1d.attributes.entity_picture
        }} {{ states.sensor.pws_weather_1d.attributes.attribution }}

        '
    service: notify.html5
- id: weather_alerts
  alias: Weather Alerts
  trigger:
  - entity_id: sensor.pws_alerts
    platform: state
  condition:
  - condition: state
    entity_id: binary_sensor.alerts_increase
    state: 'on'
  action:
  - data:
      message: Active weather alerts in Home Assistant
    service: notify.html5
- id: update_notifications
  alias: Update Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
  - service: notify.html5
    data:
      message: Update for Home Assistant is available.
