- id: weather_forecast
  alias: Weather Forecast
  trigger:
    platform: time
    hours: 5
    minutes: 30
    seconds: 0
  action:
    - service: notify.html5
      data_template:
        message: >
          The weather for {{ states.sensor.pws_weather_1d.attributes.friendly_name }} is{{ ':' }}
          {{ states.sensor.pws_weather_1d.state }}
          {{ states.sensor.pws_weather_1d.attributes.entity_picture }}
          {{ states.sensor.pws_weather_1d.attributes.attribution }}
    - service: notify.discord
      data_template:
        message: >
          The weather for {{ states.sensor.pws_weather_1d.attributes.friendly_name }} is{{ ':' }}
          {{ states.sensor.pws_weather_1d.state }}
          {{ states.sensor.pws_weather_1d.attributes.entity_picture }}
          {{ states.sensor.pws_weather_1d.attributes.attribution }}
        target: !secret discord_general_channel

- id: weather_alerts
  alias: Weather Alerts
  trigger:
    platform: numeric_state
    entity_id: sensor.pws_alerts
    value_template: '{{ state.attributes.value }}'
    above: 0
  action:
    - service: notify.discord
      data_template:
        message: >
          {{ '@everyone' }}
          {{ states.sensor.pws_alerts }}
        target: !secret discord_general_channel
    - service: notify.html5
      data:
        message: 'There are weather alerts in Discord!'
