- platform: wunderground
  api_key: !secret wunderground_key
  pws_id: !secret wunderground_id
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - weather
    - observation_time
    - temp_high_record_c
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - temp_low_record_c
    - precip_1d
    - precip_1d_mm
    - wind_kph
    - wind_1d_kph
    - alerts
- platform: fastdotcom
- platform: cert_expiry
  host: home-assistant.jeanclaudeshore.com
  port: 8123
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
- platform: google_travel_time
  api_key: !secret google_api_key
  origin: device_tracker.jc
  destination: zone.home
  options:
    units: imperial
