- platform: random
- platform: wunderground
  api_key: !secret wunderground_key
  pws_id: !secret wunderground_id
  force_update: true
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - weather
    - observation_time
    - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - temp_low_record_f
    - precip_1d
    - precip_1d_mm
    - alerts
    - pressure_in
    - relative_humidity
    - solarradiation
    - visibility_mi
    - wind_string
    - feelslike_f
- platform: fastdotcom
- platform: cert_expiry
  host: home-assistant.jeanclaudeshore.com
  port: 443
  name: HA Cert
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: memory_use
    - type: disk_use_percent
      arg: /
  force_update: true
- platform: google_travel_time
  name: JC's Phone to Home
  api_key: !secret google_api_key
  origin: device_tracker.xmfjvdpx_mk6p55
  destination: zone.home
  force_update: true
  options:
    units: imperial
- platform: google_travel_time
  name: JC's Phone to Work
  api_key: !secret google_api_key
  origin: device_tracker.xmfjvdpx_mk6p55
  destination: zone.work
  force_update: true
  options:
    units: imperial
- platform: google_travel_time
  name: JC's Phone to Laura's Apartment
  api_key: !secret google_api_key
  origin: device_tracker.xmfjvdpx_mk6p55
  destination: zone.lauras_apartment
  force_update: true
  options:
    units: imperial
- platform: mqtt
  state_topic: "owntracks/xmfjvdpx/mk6p55"
  name: "Phone Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  #- platform: fitbit
  #  monitored_resources:
  #  - activities/distance
  #  - activities/elevation
  #  - activities/steps
